apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
- ./tests/e2e-keycloak/
timeout: 90
startKIND: false
namespace: argocd-e2e-keycloak
commands:
- command: kubectl create ns argocd-e2e-keycloak
  ignoreFailure: true